# 4) გამოიყენეთ print ფუნქცია და დაბეჭდეთ თქვენთვის სასურველი მნიშვნელობები 20-ჯერ.
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
print("adamiani")
# 2) გაიცანით თქვენი ჯგუფელები, დაიმეგობრეთ, და გაუზიარეთ შთაბეჭდილებები, იმეცადინეთ ერთად, შეიყვარეთ ერთმანეთი. 
# (ვისაც გაიცნობთ, ყველას სახელი და გვარი დაპრინტეთ.)
print("gega sajaia")
print("giorgi dolidze")
print("tornike machitidze")
print("tornike wiklauri")
print("luka pailodze")
print("sandro beruasvili")
print("aleqsandre qucniasvili")
print("luka mwedlisvili")
print("mariam bogveridze")
print("giorgi kuxianize")
print("mariam tyemaladze")
print("sandro cxaize")
print("irakli waia")
print("amiko vasakidze")


